// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozubododfkoeyqpxiifl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96dWJvZG9kZmtvZXlxcHhpaWZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MTQ2NjQsImV4cCI6MjA3MjE5MDY2NH0.Id70WaEEZRYt9mYY-UY1_a6yreBa3KViCeh1-1zGGEQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});